### ISSUE TITLE
Crashes Occurring on "Feature Challenges"

### ISSUE THREAD

**Issue by rezamusic881** [ZapicInc/Zapic-SDK-Android#19]
#### Expected behavior
Supposedly, The app does not stop when I click "Feature Challenges" repeatedly.

#### Actual behavior
When I first install this app and open it, the app will immediately die. This will not happen again when I reopen the app. But the new problem I found. I try to find it, it turns out new problem is in "Challenges feature". the problem is pure crash.

#### How to reproduce
1. Instal App [here](  https://play.google.com/store/apps/details?id=com.zapic.androiddemo)
2. Run the app, click "challenges feature". Then click "back feature" or back icon.
3. Do this more than once. Then you will find crashes.

***
***

#### Recording Of The Bug
https://youtu.be/rQxpwSE27e8

#### Logcat
```
--------- beginning of crash
05-19 00:11:49.870  8709  8709 E AndroidRuntime: FATAL EXCEPTION: main
05-19 00:11:49.870  8709  8709 E AndroidRuntime: Process: com.zapic.androiddemo, PID: 8709
05-19 00:11:49.870  8709  8709 E AndroidRuntime: java.lang.IllegalStateException: A ZapicActivity has not been created
05-19 00:11:49.870  8709  8709 E AndroidRuntime: 	at com.zapic.sdk.android.i.m(Unknown Source)
05-19 00:11:49.870  8709  8709 E AndroidRuntime: 	at com.zapic.sdk.android.h.m(Unknown Source)
05-19 00:11:49.870  8709  8709 E AndroidRuntime: 	at com.zapic.sdk.android.h.handleMessage(Unknown Source)
05-19 00:11:49.870  8709  8709 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
05-19 00:11:49.870  8709  8709 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
05-19 00:11:49.870  8709  8709 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6361)
05-19 00:11:49.870  8709  8709 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-19 00:11:49.870  8709  8709 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
05-19 00:11:49.870  8709  8709 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
05-19 00:11:49.883  1464  1475 W ActivityManager:   Force finishing activity com.zapic.androiddemo/.MainActivity
```

#### Proof Of Work Done
[Submit in github](http://www.github.com/rezamusic881)

**Comment by seniorquico** [comment]
This appears to be fixed with the updated Activity/WebView management code in release 1.4.0 (this code changed significantly in release 1.4.0). The previous code did not take into account the possibility of multiple ZapicActivity instances being opened at the same time. Please reopen if you encounter this issue again.

Thanks, @rezamusic881!
